import { Router } from "express";
import { Authentication, Json, Sample, Thumbnail } from "../controllers";
import { isLoggedIn } from "../middlewares";
const router = Router();
router.get("/api", Sample.get);
router.post("/api/login", Authentication.login);
router.patch("/api/jsonpatch", isLoggedIn, Json.patch);
router.get("/api/thumbnail", isLoggedIn, Thumbnail.resize);
router.use("*", Sample.notFound);
export default router;
